### ISSUE TITLE
Unable to add external NPM packages

### ISSUE THREAD

**Issue by Tom-revere** [n8n-io/n8n#24191]
### Bug Description

Then trying to add a custom NPM package to a Docker image, I get the below error. It was working on v2.2.4, but is broken on v.2.2.5. 

```
Cannot find module ‘word-extractor’ Require stack: - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/require-resolver.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/js-task-runner.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/start.js
```

### To Reproduce

1. Use n8n v2.2.5 Docker image 

2. Create a Dockerfile with this content
```
FROM n8nio/n8n:2.2.5
USER root
RUN npm install -g word-extractor
USER node
```

3. Update docker-compose.yml to use local image:
```
services:
  n8n:
    build: .
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - 5678:5678
 ```

4. Run `docker compose build` & `docker compose up -d`

### Expected behavior

When using `require("word-extractor");` it should allow that package to be used.

### Debug Info

# Debug info

## core

- n8nVersion: 2.2.5
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 58001032-e68f-48e0-b156-b70dd2ecc922

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2026-01-12T15:18:13.585Z

### Operating System

Ubuntu 24.04

### n8n Version

2.2.5

### Node.js Version

22.21.1

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

**Comment by kepman** [comment]
+1 suddenly all my code nodes using custon packages are giving errors while they worked before.

**Comment by ahmedhassayoune** [comment]
+1 same problem with `turndown` lib

**Comment by jak119** [comment]
I'm certainly no expert with npm but if it's helpful to anyone I did try a few variations of the install including tinkering with the `NODE_PATH`:
- [Tried installing in the node_modules directory](https://github.com/jak119/n8n-jk/commit/39a29484b96d5273e90f1d859e9c879d88b23317) which failed to build
- [Use a custom modules directory and add it to `NODE_PATH`](https://github.com/jak119/n8n-jk/commit/3786439327c3b80927dab92520843c3d00319b0e) which built but **didn't solve** the issue
- [Go back to globally installing but with `--legacy-peer-deps`](https://github.com/jak119/n8n-jk/commit/5e4fb7a7d6eab40cdfaf8eec12fff93116a4d5ae) which made no difference

Ultimately I [rolled back to how I was handling the install and rolled back to 2.3.0](https://github.com/jak119/n8n-jk/commit/0f43a5fc187ac6a85498266d0f6641902adaa83c)

**Comment by remonh87** [comment]
I could find a work around for it  do the following. I used this to install mrz but replace it will the libraries you want:

```DockerFile
FROM docker.n8n.io/n8nio/n8n:2.4.6
USER root

WORKDIR /usr/local/lib/node_modules/n8n
RUN mkdir -p /tmp/npm-install && \
    cd /tmp/npm-install && \
    # Replace mrz with your lib
    npm install mrz && \ 
    cp -r node_modules/* /usr/local/lib/node_modules/n8n/node_modules/ && \
    rm -rf /tmp/npm-install

USER node
```

No errors in n8n and the code runs.

**Comment by tifandotme** [comment]
I am still stuck in 2.3.0 because of this issue

**Comment by dvnscr** [comment]
This is literally a critical issue. [PR](https://github.com/n8n-io/n8n/pull/24517) exists with one-line fix. Still, no reactions from devs.

**Comment by Donaldcwl** [comment]
This workaround works, tested on v2.8.3:
```Dockerfile
FROM n8nio/n8n:2.8.3
USER root
# Replace word-extractor with your lib
RUN npm install -g word-extractor

RUN sed -i '41i if (process.env.NODE_PATH) {\nconsole.log("Initializing node path");\nprocess.env.NODE_PATH=`/opt/nodejs/node-v22.22.0/lib/node_modules:${process.env.NODE_PATH}`;\nmodule.constructor._initPaths();\nconsole.log("Initializing node path done", process.env.NODE_PATH);\n}' /usr/local/lib/node_modules/n8n/node_modules/@n8n/task-runner/dist/start.js

USER node
```

**Comment by abdelfattahradwan** [comment]
> This workaround works, tested on v2.8.3:
> 
> FROM n8nio/n8n:2.8.3
> USER root
> \# Replace word-extractor with your lib
> RUN npm install -g word-extractor
> 
> RUN sed -i '41i if (process.env.NODE_PATH) {\nconsole.log("Initializing node path");\nprocess.env.NODE_PATH=`/opt/nodejs/node-v22.22.0/lib/node_modules:${process.env.NODE_PATH}`;\nmodule.constructor._initPaths();\nconsole.log("Initializing node path done", process.env.NODE_PATH);\n}' /usr/local/lib/node_modules/n8n/node_modules/@n8n/task-runner/dist/start.js
> 
> USER node

The same issue exists in version `2.10.2`, and the workaround above fixes it. I hope the devs can land a patch that addresses this soon 😕
