### ISSUE TITLE
Security audit doesn't work on n8n 1.17.0+

### ISSUE THREAD

**Issue by slenky** [n8n-io/n8n#8085]
**Describe the bug**
I am trying to run `n8n audit` on our self-hosted Docker n8n installations. We have n8n 1.21.0 running and it fails with this error:

```
Failed to generate security audit
Cannot find module '@/security-audit/risk-reporters/CredentialsRiskReporter'
Require stack:
- /usr/local/lib/node_modules/n8n/dist/security-audit/SecurityAudit.service.js
- /usr/local/lib/node_modules/n8n/dist/commands/audit.js
- /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/plugin.js
- /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/config.js
- /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/index.js
- /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js
- /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/index.js
- /usr/local/lib/node_modules/n8n/bin/n8n
```

Same applies if you run audit using the workflow.

I have checked n8n 1.16.0 and it seem to work without any issues.

**To Reproduce**

1. `docker run --user root -it --rm --entrypoint sh n8nio/n8n:1.21.0`
2. Run `n8n audit` and you see an error from above. 
3. `docker run --user root -it --rm --entrypoint sh n8nio/n8n:1.16.0` is the last version that seem to work.

Could it be related to #7696 ?

**Expected behavior**
`n8n audit` is working.

**Environment:**

- n8n Version 1.21.0
- Node.js Version v18.18.2

**Comment by ivov** [comment]
Should be fixed with https://github.com/n8n-io/n8n/pull/8086
