### ISSUE TITLE
Wait node executions stuck forever: `dbTime.getTime is not a function` crashes wait-tracker poller (postgres)

### ISSUE THREAD

**Issue by lucamzanon** [n8n-io/n8n#28541]
### Bug Description

 On n8n 2.16.0 and 2.17.1 with a Postgres backend, the wait-tracker poller crashes with `TypeError:
  dbTime.getTime is not a function` every 5 seconds. As a consequence, no waiting execution is ever resumed —
  every workflow that hits a Wait node stays in `waiting` status indefinitely.                                
                                                                              
  Root cause is in `packages/@n8n/db/src/repositories/clock.repository.ts` (dist:                             
  `@n8n/db/dist/repositories/clock.repository.js`). In the `getDbTime()` method, the Postgres branch returns  
  `now` directly from the raw query result instead of wrapping it in a `Date`:                              
                                                                                                              
      if (this.databaseConfig.type === 'postgresdb') {            
          const [{ now }] = await this.dataSource.query('SELECT CURRENT_TIMESTAMP(3) AS now');
          return now;                 // ← should be: return new Date(now);                   
      }                                                                                                       
      // SQLite branch correctly wraps it:                                                                    
      const [{ now }] = await this.dataSource.query("SELECT STRFTIME(...) AS now");                           
      const date = new Date(now);                                                                             
      ...                                                                                                     
      return date;                                                                                            
                                                                                                              
  Patching that single line to `return new Date(now);` fully resolves the issue — the poller stops crashing,
  backlog of waiting executions resumes correctly, new Wait-node executions complete normally.

### To Reproduce

1. Run n8n 2.16.0 or 2.17.1 with `DB_TYPE=postgresdb` (Postgres 16).
  2. Create any workflow containing a Wait node (e.g. "wait 10 seconds").
  3. Trigger the workflow.                                                                                    
  4. Observe in container logs: `dbTime.getTime is not a function` printed every 5s.                          
  5. Check DB: execution stays in `waiting` status forever; no resume, no success.     

### Expected behavior

The Wait node should pause execution for the configured interval and then resume the workflow. The          
  wait-tracker poller should not crash.

### Debug Info

Error repeats every 5s (polling interval of wait-tracker):      
                                                            
      dbTime.getTime is not a function                                                                        
                                      
  Source of the crash: `packages/cli/src/wait-tracker.ts` (dist `wait-tracker.js:64`):                        
                                                                                                              
      const [executions, dbTime] = await Promise.all([
          this.executionRepository.getWaitingExecutions(),                                                    
          this.dbClock.getApproximateDbTime(),                    
      ]);                                                                                                     
      const skewMs = dbTime.getTime() - Date.now();   // crash here                                           
                                                                                                              
  `DbClock.getApproximateDbTime()` calls `ClockRepository.getDbTime()` which in the Postgres branch returns   
  the raw query field instead of a Date instance.                                                             
                                                                                                              
  Workaround verified: editing `clock.repository.js` to `return new Date(now);` in the postgres branch,       
  restarting the container — poller stops crashing, all stuck waiting executions resume, backlog drains, new  
  Wait nodes complete normally.

### Operating System

Ubuntu Linux (host kernel 5.4), n8n inside Docker (Alpine image)

### n8n Version

2.17.1 (also reproduced on 2.16.0) 

### Node.js Version

24.14.1 (shipped in the official n8n Docker image)  

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

**Comment by zhendery** [comment]
same, fallback to 2.15.1 no this problem

**Comment by artem-levashov** [comment]
I have this problem on 2.15.1 and 2.16.0.  The only differnes it is not happeneing immidiatly.  after some time  contaier logs starts show that error and  none of  workflows with Wait node cannot finish execution.  after restart container it works again. all stuck execuitions  finish job successfully and work good some time.  but at some moment it just stop working.  I don't see any reason that could trigger  that problem. we just use that node in single workflow  but often during the day.

**Comment by online** [comment]
I am also encountering this issue on **n8n v2.16.1**. Even after removing Wait nodes from all my active workflows, the error `dbTime.getTime is not a function` continues to appear in the logs (checked via `docker logs -f n8n`). 

Could you please advise on a temporary workaround or a patch for this? It seems the poller continues to crash regardless of whether there are active waiting executions or not.

**Comment by dwassano** [comment]
Thanks, applied the suggested workaround at n8n v2.16.1 running in docker and it works.

Here is a script to apply this workaround:

ssh to n8n container and run:
```
cp /usr/local/lib/node_modules/n8n/node_modules/@n8n/db/dist/repositories/clock.repository.js \
   /usr/local/lib/node_modules/n8n/node_modules/@n8n/db/dist/repositories/clock.repository.js.bak

sed -i 's/return now;/return new Date(now);/' \
  /usr/local/lib/node_modules/n8n/node_modules/@n8n/db/dist/repositories/clock.repository.js

grep -n "return new Date(now)" \
  /usr/local/lib/node_modules/n8n/node_modules/@n8n/db/dist/repositories/clock.repository.js
```

Then restart n8n.

**Comment by membrive** [comment]
Same issue here with version `2.17.2`. I downgraded to `2.14.2` using Docker, and the error is gone.

**Comment by Dinhmanh96** [comment]
Same issue!

**Comment by WebleyA** [comment]
Same

**Comment by icoari** [comment]
Same issue!

**Comment by nachokhan** [comment]
same issue!

**Comment by kent-1** [comment]
I'm having the same issue. I also noticed that workflows with the "do not save" setting remain in the PostgreSQL database as "running" indefinitely. When I changed the setting to "save," the execution status was updated and they no longer stayed stuck in the "running" state in the database.

**Comment by hananah** [comment]
same issue!
[The Wait node never resumes](https://github.com/n8n-io/n8n/issues/28664#top)

**Comment by MatCalixto** [comment]
same issue

**Comment by kostaks-a** [comment]
Same here, we solved it by using the following on a code node in JS:

```
await new Promise(resolve => setTimeout(resolve, 2000));
return $items();
```

**Comment by wv-martijn** [comment]
Got the same issue on 2.16.1 and 2.17.3.
`dbTime.getTime is not a function`

**Comment by fokc1509** [comment]
+1 here, downgraded to  2.14.2

**Comment by ivov** [comment]
Thanks all for raising this. At 2.17.3 I cannot reproduce this anymore, either regular or queue mode with Postgres.

@wv-martijn mentioned this still being broken at that version, can you double check?

**Comment by fokc1509** [comment]
updated to 2.17.3 -  problem stopped and workflows with wait node are working properly.

**Comment by gabrielrouss** [comment]
Same error here, returning to 2.16.1 was resolved, but just to make it run again...

**Comment by diego-borja** [comment]
Same error in Wait node

**Comment by paramedicspecialist** [comment]
> Got the same issue on 2.16.1 and 2.17.3. `dbTime.getTime is not a function`

I am also getting that same error after upgrading to 2.17.3, as an interim measure we've changed all our wait nodes to a JS function.

`Apr 21 23:04:56 dbTime.getTime is not a function`

**Comment by ivov** [comment]
> > Got the same issue on 2.16.1 and 2.17.3. `dbTime.getTime is not a function`
> 
> I am also getting that same error after upgrading to 2.17.3, as an interim measure we've changed all our wait nodes to a JS function.
> 
> `Apr 21 23:04:56 dbTime.getTime is not a function`

Thanks for the reply. Checked internally and we'll soon backport the fix to 2.17.4.

**Comment by thabelo** [comment]
@ivov whats the ETA for 2.17.4 with the fix?

**Comment by d-schl-iits** [comment]
> [@ivov](https://github.com/ivov) whats the ETA for 2.17.4 with the fix?

it already landed: https://github.com/n8n-io/n8n/releases/tag/n8n%402.17.4

**Comment by thabelo** [comment]
@ivov @d-schl-iits thank you

**Comment by ivov** [comment]
Closing, let us know if this comes up again and we'll reopen.

**Comment by kent-1** [comment]
Not tried in v2.17.4 yet, but in v2.17.3 the issue was still present. I will try tomorrow with v2.17.4 and let you know. On v2.17.3 the issue appears after a while (approximately 10 hours).

**Comment by membrive** [comment]
I have just updated to v2.17.5, and the issue is now resolved. It is included in the changelog. Thank you, n8n team!
