### ISSUE TITLE
Update from 1.123.6 to 1.123.61 -> using prom-client in code node broken

### ISSUE THREAD

**Issue by glappsi** [n8n-io/n8n#33646]
### Bug Description

We recently updated from 1.123.6 to 1.123.61. We are having a OTEL workflow to track custom metrics which uses the code node and the internally used prom-client library like so const client = require('prom-client');. This does not work anymore due to the error “Cannot find module ‘prom-client’”. We enabled N8N_METRICS and also set NODE_FUNCTION_ALLOW_EXTERNAL to "prom-client". This worked in 1.123.6.

### To Reproduce

Please have a look at https://community.n8n.io/t/update-from-1-123-6-to-1-123-61-using-prom-client-in-code-node-broken/302275

### Expected behavior

`prom-client` being available.

### Debug Info

More info: https://community.n8n.io/t/update-from-1-123-6-to-1-123-61-using-prom-client-in-code-node-broken/302275

### Operating System

linux/amd64 (docker on render.com)

### n8n Version

1.123.61

### Node.js Version

24.13.1

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted
