### ISSUE TITLE
MCP update_workflow / validate_workflow fail with "builder.regenerateNodeIds is not a function"

### ISSUE THREAD

**Issue by eldinerointeligente2023-ai** [n8n-io/n8n#28051]
**Environment**
- n8n Cloud version: 2.14.2
- MCP server endpoint: `https://[instance].app.n8n.cloud/mcp-server/http`
- Integration: Claude AI via MCP connector (Claude.ai)

**Description**

All three workflow modification tools exposed via the n8n MCP server fail consistently with the same internal error:

```
Failed to parse generated workflow code: builder.regenerateNodeIds is not a function
```

This affects:
- `validate_workflow`
- `update_workflow`
- `create_workflow_from_code`

The error occurs at the internal SDK parsing stage, before any workflow logic is evaluated. It is not related to the code format or content — the error reproduces with the most minimal possible input.

**Steps to Reproduce**

Call `validate_workflow` via MCP with the following minimal code:

```js
const myFlow = {
  name: "TEST",
  nodes: [
    {
      id: "sticky-test",
      name: "Test Note",
      type: "n8n-nodes-base.stickyNote",
      typeVersion: 1,
      position: [100, 100],
      parameters: { content: "Hello", height: 200, width: 300, color: 3 }
    }
  ],
  connections: {}
};
export default myFlow;
```

**Expected Result**
Workflow validates successfully and returns the parsed workflow JSON.

**Actual Result**
```json
{
  "valid": false,
  "errors": [
    "Failed to parse generated workflow code: builder.regenerateNodeIds is not a function"
  ]
}
```

**Additional Notes**
- The error is 100% reproducible across all code formats tested (with/without imports, with/without `export default`, plain objects, single nodes, multiple nodes)
- Tested before and after upgrading to v2.14.2 — bug persists
- Read-only MCP tools (`search_workflows`, `get_workflow_details`, `get_execution`) work correctly — only write tools are affected
- The `builder` object referenced in the error message appears to be missing the `regenerateNodeIds` method in the version of the Workflow SDK bundled with the MCP server

**Workaround**
None available via MCP. Workflow modifications must be done manually through the n8n UI.

**Comment by eldinerointeligente2023-ai** [comment]
Related issue: https://github.com/n8n-io/n8n/issues/27874
This is a known open bug on n8n's official GitHub repository (opened March 31, 2026). The issue confirms that update_workflow and create_workflow_from_code MCP tools produce empty workflows regardless of the node format used. Tested on n8n 2.13.4 and confirmed still present on 2.14.2.

**Comment by MiloradFilipovic** [comment]
Hey @eldinerointeligente2023-ai 
Thanks for reporting, we are currently working on addressing this issue.
From your report, looks like you are passing a JSON object to `validate` tool (also `update_workflow` and `create_workflow_from_code` which use the same validation logic under the hood), which only accepts workflow-SDK code (typescript). Can you confirm this?
