### PR TITLE
fix(core): Prevent duplicate zod instances that break npm installs

### PR DESCRIPTION
**Pull request by Matsuuu**
## Summary

Since **2.28.0**, `npm install n8n` crashes at boot. Reproduced with a clean `npm install n8n@2.28.0` → `n8n`:

```
Error: A discriminator value for key `__type` could not be extracted from all schema options
  at .../@n8n/api-types/node_modules/zod/.../v3/types.js
  at .../@n8n/api-types/dist/dto/log-streaming/create-destination.dto.js   // z.discriminatedUnion('__type', [...])
```
(surfaced to users as a misleading `Cannot find module .../breaking-changes.ee/breaking-changes.module`.)

**Root cause — duplicate `zod` instances.** `@n8n/api-types` builds a `z.discriminatedUnion` over option schemas created inside `n8n-workflow`. That only works when both packages resolve the **same physical zod copy**. #32386 ("Extraneous deps cleanup", in 2.28.0) moved `zod` from `peerDependencies` into `dependencies` in several backend packages, reverting #28604 ("Ensure single zod instance across workspace packages"). On npm this causes duplication: `@langchain/*` pins `zod@4` at the tree root, so every `@n8n/*` package that lists `zod` in `dependencies` gets its **own nested `zod@3`** copy → cross-package schema composition resolves different instances → crash. The pnpm monorepo is unaffected because the catalog forces a single hoisted instance, which is why it only broke npm consumers / not docker.

**Fix.** Restore `zod` to `peerDependencies` (+ `devDependencies`) in the backend packages that share zod schemas across boundaries — `@n8n/api-types`, `n8n-workflow`, `n8n-core`, `@n8n/agents` — so the consuming app provides one shared instance (langchain keeps its own separate zod, which is harmless since it never shares schema objects with n8n's discriminated unions). Also allow peer-dependency imports in the shared eslint config (`import-x/no-extraneous-dependencies`), and add `scripts/check-zod-peer-deps.mjs` (wired via `pnpm check:zod-peer-deps` and a lefthook pre-commit hook) so a future "deps cleanup" cannot silently move `zod` back into `dependencies`.

This keeps `zod` pinned at `3.25.67` — no version bump, so there is no type-inference churn in the LangChain/MCP integration code.

## How to test

Verified end-to-end via a local npm registry (verdaccio) publishing this branch:

- `npm install n8n@<branch>` then `require('@n8n/api-types')` → loads cleanly (previously threw the discriminatedUnion error).
- `@n8n/api-types` and `n8n-workflow` resolve **the same** `node_modules/zod@3.25.67`; `@langchain/*` gets its own isolated `zod@4`.
- Booting n8n from the monorepo reaches `n8n ready on ...`, runs all migrations, and loads every module (incl. `breaking-changes`) with no crash.
- Repo-wide typecheck (100 packages) and lint on the four packages pass.
- Regression guard: `pnpm check:zod-peer-deps` passes; it fails if `zod` is moved back into `dependencies` in any of the four packages.

## Related Linear tickets, Github issues, and Community forum posts

- Regression from #32386; restores the approach of #28604.
- Related community report: https://community.n8n.io/t/n8n-install-issue-im-installing-from-2-02-version-to-2-28-4-the-issue-is-im-getting-start-not-found/301740

## Review / Merge checklist

- [x] I have seen this code, I have run this code, and I take responsibility for this code.
- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
- [ ] PR Labeled with `Backport to Beta`, `Backport to Stable`, or `Backport to v1` (if the PR is an urgent fix that needs to be backported)

🤖 PR Summary generated by AI

<a href="https://cubic.dev/pr/n8n-io/n8n/pull/33463?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

---

<a href="https://stagereview.app/n8n-io/n8n/pull/33463">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://stagereview.app/assets/gh-open-in-stage-dark.svg">
    Open in Stage
  </picture>
</a>

### CODE REVIEW

**Review by CharlieKolb — APPROVED** [review]
Love that we're adding a script to check for this!
