### ISSUE TITLE
After update to 1.120.3 -> window.crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by Estradamis** [n8n-io/n8n#22017]
### Bug Description

After my docker container updated an hour ago, I cannot make any further changes to my n8n workflows. Everytime I am getting the error:
`window.crypto.randomUUID is not a function`

### To Reproduce

1. Open any workflow
2. Add e.g. a node (for example "If")
3. Get error

### Expected behavior

Node to be created 

### Debug Info

# Debug info

## core

- n8nVersion: 1.120.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: c6d37793-a51a-4765-a0f6-48cfc43224a2

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

## security

- secureCookie: false

Generated at: 2025-11-18T21:20:40.915Z

### Operating System

Docker on Ubuntu 22.04.4 LTS

### n8n Version

1.120.3

### Node.js Version

Don'T know

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

**Comment by Catsofsuffering** [comment]
same issue to me, so is there any update?

**Comment by cui369680775** [comment]
same issue to me，same version。

**Comment by wifiuk** [comment]
same issue.

n8n Version
1.120.3

**Comment by NeilBain** [comment]
Same problem.  Additionally:
Occurs in Safari and Chrome;
Pinning docker to previous version restores functionality (Precisely, `image: docker.n8n.io/n8nio/n8n:1.119.2` in compose.yml

**Comment by bnknkyl** [comment]
Hi, can confirm I'm seeing this in Edge on Version 1.120.3

**Comment by thelakemann** [comment]
I'm also on version 1.120.3, experiencing the same error, and I logged out to see if that was the cause.
Now I can't access the system at all.

Error message: Error connecting to n8n. Could not connect to server. Refresh to try again.
Restarting doesn't help. Deleting cookies doesn't help either.

Update: Version 1.120.4 brings no changes.

--

I restored an older version from a backup (Proxmox VM).

It did produce the same error when modifying a node, but after shutting down the machine, I was able to access my original machine again. I'm not going to log out again for now :)
So it seems to be some kind of cache issue, even though I cleared the cache and tried different browsers.

Additional info: When restoring a machine that's about two weeks old, everything is generally fine, but the error occurs when updating to the latest version.

**Comment by dojoca** [comment]
Same issue here. 

Just to add - downgrading to 1.119.2 got it working again for me. Also restarting my browser (Firefox), or it kept saying it couldn't conenct to N8N.

**Comment by langren1353** [comment]
I follow this，and changed to next version, it is ok：
```
# Pull latest (stable) version
docker pull docker.n8n.io/n8nio/n8n

# Pull specific version
docker pull docker.n8n.io/n8nio/n8n:1.81.0

# Pull next (unstable) version
docker pull docker.n8n.io/n8nio/n8n:next
```

**Comment by tameike000** [comment]
Same issue::
1.119.x works
1.120.x issue occurs

no changes to the setup/configuration

**Comment by jborut** [comment]
Same here. I am hosting on http, not https, so my guess this has to do with that.

**Comment by NeilBain** [comment]
Appears fixed in 1.120.4

**Comment by tameike000** [comment]
checked with 1.120.4
not fixed for me at least

**Comment by Rafa2697** [comment]
i was using 1.120.2, i had to go back to 1.119.2

**Comment by masterwebsk** [comment]
I just tested 1.120.4 on two instances and found that on one instance without https it really dont work. but with https it was working. Can somebody confirm this ?
on instance without https i downgraded to 1.119.2 and is ok. will wait for fix for non https.

**Comment by stealthm0d3** [comment]
On 1.120.4, same error, no fix.

**Comment by poparotsy** [comment]
I’m experiencing the same issue when attempting to import a workflow JSON file after upgrading to version 1.120.4.  Later, I discovered that the problem primarily stems from accessing a self-hosted N8N instance over HTTP instead of HTTPS. The AI documentation acknowledges this as a known issue.

As a quick workaround, I found that running the following function in the browser console resolves the issue temporarily, but it will eventually occur again.

```javascript
window.crypto.randomUUID = function() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};
```

A more sustainable solution is to configure N8N behind a proxy and enable SSL, whether it’s self-signed or you have a domain to use in your home lab network.

I believe it would be more convenient if they released these Docker images and LXC containers with a working nginx proxy configured with a self-signed certificate pre-installed. This would be particularly helpful for newcomers.

For reference, the server wasn’t accessible through Chrome or Safari; it was only accessible through Firefox, where the error mentioned earlier occurred.

**Comment by AdaHsu** [comment]
Interesting finding: The issue does not occur when accessing externally via Cloudflare Tunnel (https://n8n.example.com/), but the anomaly persists when accessing via the internal network (http://ubuntu:5678/).

**Comment by wifiuk** [comment]
It does happen using cloudflare tunnel with n8n self hosted using http

**Comment by sven-debug** [comment]
> I just tested 1.120.4 on two instances and found that on one instance without https it really dont work. but with https it was working. Can somebody confirm this ? 

I can, same behaviour here. https working, http not.

**Comment by yanchuk** [comment]
the same. using locally (self-host) http and adding https via Cloudflare tunnel

**Comment by teaglebuilt** [comment]
if you setup certs so you can access over 443 then would you still get the error? Are you setting `N8N_PROTOCOL`?

**Comment by poparotsy** [comment]
> if you setup certs so you can access over 443 then would you still get the error? Are you setting `N8N_PROTOCOL`?
 
I installed nginx on the same host with a self-signed certificate.

```JavaScript

server {
    listen 8443 ssl;
    server_name localhost 192.168.1.*;

    ssl_certificate /etc/nginx/ssl/n8n.crt;
    ssl_certificate_key /etc/nginx/ssl/n8n.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:5678;

```

**Comment by david-hollingworth** [comment]
> > if you setup certs so you can access over 443 then would you still get the error? Are you setting `N8N_PROTOCOL`?
> 
> I installed nginx on the same host with a self-signed certificate.
> 
> server {
>     listen 8443 ssl;
>     server_name localhost 192.168.1.*;
> 
>     ssl_certificate /etc/nginx/ssl/n8n.crt;
>     ssl_certificate_key /etc/nginx/ssl/n8n.key;
>     ssl_protocols TLSv1.2 TLSv1.3;
>     ssl_ciphers HIGH:!aNULL:!MD5;
> 
>     location / {
>         proxy_pass http://localhost:5678;

Did this resolve the issue for you? 

When you said the same 'host' is this installed in the same container as n8n?

Thanks

**Comment by poparotsy** [comment]
> > if you setup certs so you can access over 443 then would you still get the error? Are you setting `N8N_PROTOCOL`?
> 
> I installed nginx on the same host with a self-signed certificate.
> 
> server {
>     listen 8443 ssl;
>     server_name localhost 192.168.1.*;
> 
>     ssl_certificate /etc/nginx/ssl/n8n.crt;
>     ssl_certificate_key /etc/nginx/ssl/n8n.key;
>     ssl_protocols TLSv1.2 TLSv1.3;
>     ssl_ciphers HIGH:!aNULL:!MD5;
> 
>     location / {
>         proxy_pass http://localhost:5678;

**This configuration works just as well.** 
```JavaScript
#n8n.env
N8N_SECURE_COOKIE=true
N8N_PORT=5678
N8N_PROTOCOL=https
N8N_HOST=192.168.1.123
N8N_SSL_CERT=/path/to/n8n.crt
N8N_SSL_KEY=/path/to/n8n.key
```

**Comment by poparotsy** [comment]
> > > if you setup certs so you can access over 443 then would you still get the error? Are you setting `N8N_PROTOCOL`?
> > 
> > 
> > I installed nginx on the same host with a self-signed certificate.
> > server {
> > listen 8443 ssl;
> > server_name localhost 192.168.1.*;
> > ```
> > ssl_certificate /etc/nginx/ssl/n8n.crt;
> > ssl_certificate_key /etc/nginx/ssl/n8n.key;
> > ssl_protocols TLSv1.2 TLSv1.3;
> > ssl_ciphers HIGH:!aNULL:!MD5;
> > 
> > location / {
> >     proxy_pass http://localhost:5678;
> > ```
> 
> Did this resolve the issue for you?
> 
> When you said the same 'host' is this installed in the same container as n8n?
> 
> Thanks

Same host, VM installation, not docker.

**Comment by david-hollingworth** [comment]
Thank you.  This worked for me:

#n8n.env
N8N_SECURE_COOKIE=true
N8N_PORT=5678
N8N_PROTOCOL=https
N8N_HOST=192.168.1.123
N8N_SSL_CERT=/path/to/n8n.crt
N8N_SSL_KEY=/path/to/n8n.key

Best regards
