### ISSUE TITLE
Task runner cannot find puppeteer in v2

### ISSUE THREAD

**Issue by JLHSolutions** [n8n-io/n8n#24196]
### Bug Description

I'm having trouble using puppeteer in n8n v2 Code nodes. It works perfectly in v1.123.7 but v2's task runner can't find the module even when properly installed and allowlisted.

Environment: NODE_FUNCTION_ALLOW_EXTERNAL=puppeteer
Error: Cannot find module 'puppeteer' from @n8n/task-runner

Has anyone successfully used puppeteer with v2's task runner? Is there additional configuration needed?

### To Reproduce

Setup and use puppeteer in v1. Upgrade to v2 and it breaks.

### Expected behavior

In V1.123.7, the code works, goes to the website, extracts the HTML code, parses for particular information and the workflow continues. In V2, it just fails every single time. 

### Debug Info

- n8nVersion: 2.3.2
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)

### Operating System

MacOS 15.7.3

### n8n Version

2.3.2

### Node.js Version

22.21.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

**Comment by MookieLian** [comment]
<aside>

Thanks for bringing this up! After reviewing the details, it seems like the behaviour you've reported is actually expected and not a bug. We can understand how this might seem confusing, so we've added a note to clarify things.

If you have any questions or need more details, feel free to reach out again, we're here to help!

_Note that since v2, n8n enables external task runners by default for security reasons; third-party modules are configured in the **env-overrides** section inside the `n8n-task-runners.json` file. Refer to the official documentation on [setting up an external task runner](https://docs.n8n.io/hosting/configuration/task-runners/#configuring-launcher-in-runners-container-in-external-mode) for more information._

`#closed:working-as-expected`

</aside>

**Comment by dvnscr** [comment]
Same. I.e. tried openpgp module. runner error says "Allowlisted module 'openpgp' is not installed".
