### ISSUE TITLE
Existing Google OAuth Credentials fail with "Dummy.stack.replace" until reconnected

### ISSUE THREAD

**Issue by relkli** [n8n-io/n8n#23182]
### Bug Description

After upgrading from `1.118.2` to `1.121.2`, my **existing** workflows involving Google Sheets/Slides nodes (using **Credential Overwrite**) started failing with the error:
`TypeError: Dummy.stack.replace is not a function`.

The error did not appear immediately after the upgrade. My workflows continued to work correctly for approximately **24 hours**. After this period, they started failing consistently.

1. **Rollback works:** If I downgrade back to `1.118.2`, the workflows start working again immediately **without** needing to reconnect. This proves the credentials in the database are valid.
2. **Reconnect works:** If I stay on `1.121.2` and manually reconnect/re-authenticate the Google credentials, the issue is resolved.

**Environment:**
- **n8n Version:** 1.121.2 (Issue exists), 1.118.2 (Works)
- **Node Type:** Google Sheets / Google Slides
- **Auth Type:** OAuth2 with Credential Overwrite

**References:**
- Related issue: https://github.com/n8n-io/n8n/issues/20946
- Community reports:
    - https://community.n8n.io/t/another-dummy-stack-replace-is-not-a-function-error-post/234111
    - https://community.n8n.io/t/dummy-stack-replace-is-not-a-function/198291/4

### To Reproduce

1. Have an n8n instance on version `1.118.2` with an active workflow using Google Sheets/Slides (configured with **Credential Overwrite**).
2. Upgrade the instance to `1.121.2`.
3. Wait for approximately 24 hours.
4. Execute the existing workflow (without editing it).
5. Execution fails with: `Dummy.stack.replace is not a function`.
### Expected behavior

The upgrade should be backward compatible. Existing credentials that work in `1.118.2` should continue to work in `1.121.2` without requiring manual reconnection.

### Debug Info
```
# Debug info

## core

- n8nVersion: 1.118.2
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: postgres
- executionMode: scaling (single-main)
- concurrency: -1

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false
```
### Operating System

EKS 1.31

### n8n Version

1.121.2

### Node.js Version

Bundled in Docker image `n8nio/n8n:1.121.2`

### Database

PostgreSQL

### Execution mode

queue

### Hosting

self hosted

**Comment by relkc** [comment]
@Joffcom, could you please take a look at this? Thank you.
