### ISSUE TITLE
Command `npm run build` is failing

### ISSUE THREAD

**Issue by dokime7** [n8n-io/n8n#1947]
**Describe the bug**
The command `npm run build` is failing with:

```
> build
> lerna exec npm run build

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run build"

> n8n-workflow@0.62.0 build
> tsc

error TS2688: Cannot find type definition file for 'jest'.
  The file is in the program because:
    Entry point of type library 'jest' specified in compilerOptions

  tsconfig.json:9:4
    9    "jest"
         ~~~~~~
    File is entry point of type library specified here.


Found 1 error.

lerna ERR! npm run build exited 2 in 'n8n-workflow'
lerna ERR! npm run build exited 2 in 'n8n-workflow'

```

**To Reproduce**
Just run the above command just after `lerna bootstrap --hoist` and `npm install --force` on a fresh git clone.

**Expected behavior**
Success of command.

**Environment (please complete the following information):**
- OS: Ubuntu 21.04
- n8n Version: dev
- Node.js Version: v16.4.0
- Database system: SQLite
- Operation mode: own
- Npm Version: 7.18.1

**Additional context**
Maybe related to https://github.com/n8n-io/n8n/issues/1946 because I forced npm install due to lerna bootstrap failing with conflict on eslint.

**Comment by janober** [comment]
Thanks for reporting but this is probably related to Node.js v16 and npm v7. Right now we only officially support Node.js v14 with npm v6. Everything else will cause problems because of dependencies of n8n.

Regarding the npm v7 problem you can try: `npm config set legacy-peer-deps true`
as mentioned in the comment of #1946 but not sure if that will fix all the problems.

**Comment by dokime7** [comment]
Thanks, it's working with node v14.17.1 :)

**Comment by janober** [comment]
Glad to hear! Have fun!

**Comment by M1kep** [comment]
@janober It would be very helpful if the Contributing guide included these version requirements
