### PR TITLE
fix: Task Runner Initialize NODE_PATH for external npm packages

### LINKED ISSUE #24191: Unable to add external NPM packages
### Bug Description

Then trying to add a custom NPM package to a Docker image, I get the below error. It was working on v2.2.4, but is broken on v.2.2.5. 

```
Cannot find module ‘word-extractor’ Require stack: - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/require-resolver.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/js-task-runner.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/start.js
```

### To Reproduce

1. Use n8n v2.2.5 Docker image 

2. Create a Dockerfile with this content
```
FROM n8nio/n8n:2.2.5
USER root
RUN npm install -g word-extractor
USER node
```

3. Update docker-compose.yml to use local image:
```
services:
  n8n:
    build: .
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - 5678:5678
 ```

4. Run `docker compose build` & `docker compose up -d`

### Expected behavior

When using `require("word-extractor");` it should allow that package to be used.

### Debug Info

# Debug info

## core

- n8nVersion: 2.2.5
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 58001032-e68f-48e0-b156-b70dd2ecc922

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2026-01-12T15:18:13.585Z

### Operating System

Ubuntu 24.04

### n8n Version

2.2.5

### Node.js Version

22.21.1

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by bpk9**
## Summary
- Added call to `module.constructor._initPaths()` in task runner to initialize module paths from `NODE_PATH` environment variable

## Related tickets and issues
- Fixes #24191

## Review / Merge checklist
- [ ] PR title and target branch are set correctly
- [ ] Docs updated or follow-up ticket created
- [ ] Tests are passing
- [ ] Contributor checklist completed

## Details

The issue was that while `NODE_PATH` environment variable was passed to the task runner process (since commit 906770a), Node.js doesn't automatically pick up changes to `NODE_PATH` after the process starts.

This fix adds the same `_initPaths()` call that exists in `load-nodes-and-credentials.ts` to ensure the module resolution system is properly initialized with the paths from `NODE_PATH`. This enables external npm packages installed in custom locations (like in Docker) to be found by `require()` calls.

### CODE REVIEW

**Comment by nepomuc** [comment]
Please merge this soon!

**Comment by a3sroot** [comment]
@shortstacked

**Review by shortstacked — APPROVED** [review]
PR looks good. Follows the same patterns as expected. Thanks!
