### PR TITLE
fix(core): Preserve NODE_PATH for globally installed npm packages in Docker

### LINKED ISSUE #24191: Unable to add external NPM packages
### Bug Description

Then trying to add a custom NPM package to a Docker image, I get the below error. It was working on v2.2.4, but is broken on v.2.2.5. 

```
Cannot find module ‘word-extractor’ Require stack: - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/require-resolver.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/js-task-runner/js-task-runner.js - /usr/local/lib/node_modules/n8n/node_modules/.pnpm/@n8n+task-runner@file+packages+@n8n+task-runner_@opentelemetry+api@1.9.0_@opentelemetry_eb51b38615a039445701c88b088f88d0/node_modules/@n8n/task-runner/dist/start.js
```

### To Reproduce

1. Use n8n v2.2.5 Docker image 

2. Create a Dockerfile with this content
```
FROM n8nio/n8n:2.2.5
USER root
RUN npm install -g word-extractor
USER node
```

3. Update docker-compose.yml to use local image:
```
services:
  n8n:
    build: .
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./data:/home/node/.n8n
    ports:
      - 5678:5678
 ```

4. Run `docker compose build` & `docker compose up -d`

### Expected behavior

When using `require("word-extractor");` it should allow that package to be used.

### Debug Info

# Debug info

## core

- n8nVersion: 2.2.5
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.1
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 58001032-e68f-48e0-b156-b70dd2ecc922

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/143.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2026-01-12T15:18:13.585Z

### Operating System

Ubuntu 24.04

### n8n Version

2.2.5

### Node.js Version

22.21.1

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

### PR DESCRIPTION
**Pull request by shortstacked**
## Summary
- `load-nodes-and-credentials.ts` was clobbering `process.env.NODE_PATH` with `module.paths`, destroying the Docker-configured value needed for globally installed packages (e.g. `npm install -g word-extractor`)
- This caused the task runner's `require()` to fail with "Cannot find module" for any externally installed package in both internal mode (child process) and external mode (sidecar container)
- Fixes by appending existing NODE_PATH instead of replacing it, and adds NODE_PATH to the runner launcher's `allowed-env` list

## Root Cause
In `load-nodes-and-credentials.ts:71`, `process.env.NODE_PATH` was being overwritten with `module.paths.join(delimiter)`. In Docker, the DHI base image sets `NODE_PATH=/opt/nodejs/node-v.../lib/node_modules` so that globally installed packages are resolvable. This clobbering replaced that path with only n8n internal paths, so when the task runner subprocess inherited `NODE_PATH`, it could no longer find global packages.

Three prior fix attempts (PRs #24517, #24765, DHI Dockerfile changes) were insufficient because they all assumed NODE_PATH would survive through to the task runner — but this clobbering happened after Docker ENV was set and before the task runner was spawned.

## Changes
| File | Change |
|------|--------|
| `packages/cli/src/load-nodes-and-credentials.ts` | Append existing NODE_PATH instead of replacing |
| `docker/images/runners/n8n-task-runners.json` | Add NODE_PATH to `allowed-env` for external runner mode |
| `packages/@n8n/task-runner/.../require-resolver-global-modules.test.ts` | New: 5 regression tests for NODE_PATH + _initPaths behavior |
| `packages/cli/src/__tests__/load-nodes-and-credentials.test.ts` | New: 2 tests for NODE_PATH preservation logic |

## Test plan
- [x] New regression test suite (5 cases) verifies require() behavior with/without NODE_PATH
- [x] NODE_PATH preservation unit tests verify append-not-clobber logic
- [x] Existing load-nodes-and-credentials tests still pass (30/30)
- [x] Manual Docker verification: build custom image with `npm install -g <package>`, confirm Code node can `require()` it

Closes https://github.com/n8n-io/n8n/issues/24191

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by dariacodes — APPROVED** [review]

**Comment by GauthierPLM** [comment]
Hello @shortstacked @dariacodes,
Could this be backported to v1.123?
It seems there was a regression between minor versions and this would fix it, as currently globally installed packages can't be used anymore in code nodes.

**Comment by Matsuuu** [comment]
Hi @GauthierPLM !

This fix has been backported to v1, and will be released in tomorrow's patch release.

https://github.com/n8n-io/n8n/pull/28781
