### PR TITLE
fix: Pin @ibm-cloud/watsonx-ai to ^1.7.9 to restore /gateway subpath

### PR DESCRIPTION
**Pull request by schrothbn**
## Summary

`@langchain/community` statically imports from `@ibm-cloud/watsonx-ai/gateway` in its IBM embeddings module, but pnpm was auto-installing the wildcard peer dep at v1.1.2 — which predates the `/gateway` subpath export. Any custom node that triggered `@langchain/community/embeddings/ibm` failed with:

```
Cannot find module '@ibm-cloud/watsonx-ai/gateway'
```

Reported by an enterprise customer (IBM X-Force) after upgrading from 2.6.4 to 2.11.3; affects 2.11.3 through 2.14.2.

### Why a direct dependency instead of a pnpm override

The ticket suggested a root `pnpm.overrides` entry, but pnpm 10.32 does not re-resolve auto-installed peer dependencies through overrides (verified with `--force` and `--fix-lockfile`). Declaring `@ibm-cloud/watsonx-ai: ^1.7.9` as a direct dep in the two workspace packages that consume `@langchain/community` (`@n8n/nodes-langchain` and `@n8n/ai-utilities`) satisfies the peer in a way pnpm honors, and is the canonical fix.

The latest `@langchain/community` (1.1.28) still declares `@ibm-cloud/watsonx-ai` only as a wildcard peer — pinning on the consumer side is required.

### How to test

```bash
node -e "console.log(require.resolve('@ibm-cloud/watsonx-ai/gateway', { paths: ['packages/@n8n/nodes-langchain'] }))"
node -e "console.log(Object.keys(require('@langchain/community/embeddings/ibm')))"
```

Both should succeed; the second prints `['WatsonxEmbeddings', 'ibm_exports']`.

n8n itself ships no Watsonx node and has no source code that imports watsonx-ai — only community/custom nodes are affected.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/AI-2295

## Review / Merge checklist

- [x] I have seen this code, I have run this code, and I take responsibility for this code.
- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
- [ ] PR Labeled with `Backport to Beta`, `Backport to Stable`, or `Backport to v1` (if the PR is an urgent fix that needs to be backported)

🤖 PR Summary generated by AI

### CODE REVIEW

**Comment by jeanpaul** [comment]
Decided against this as per slack thread!
